platform:
  - x64

environment:
  matrix:
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --verbose --target=%TARGET%
