#image: scorpil/rust:stable
image: rust:latest

pipelines:
  default:
    - step:
        script:
          #- echo "Updates to rustup"                ; rustup self update
          #- echo "Update Rust toolchain"            ; rustup update
          - echo "Print Rust toolchain version"     ; rustc -vV ; cargo -vV
          #- echo "Setup git with read/write access" ; ./scripts/setup-git.sh
          - echo "Build project"                    ; cargo build
          #- echo "Format source code"               ; ./scripts/fmt.sh
          - echo "Run unit tests"                   ; cargo test -v --no-fail-fast -- --nocapture --test
          - echo "Run documentation tests"          ; cargo test --doc -v --no-fail-fast -- --nocapture --test
          #- echo "Run integration tests"            ; cargo test --test ${CARGO_LIB_NAME} -v --no-fail-fast -- --nocapture --test
          #- echo "Run benchmark tests"              ; cargo test --lib --release -v --no-fail-fast -- --nocapture --bench
          #- echo "Publish documentation"            ; ./scripts/docs.sh
          #- echo "Upload to crates.io"              ; ./scripts/crates-io.sh
          